Traceback (most recent call last):
  File "/Users/Martin/opt/miniconda3/envs/wintest/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/Martin/opt/miniconda3/envs/wintest/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/Martin/opt/miniconda3/envs/wintest/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/Martin/opt/miniconda3/envs/wintest/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/Martin/opt/miniconda3/envs/wintest/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/Martin/opt/miniconda3/envs/wintest/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/Martin/opt/miniconda3/envs/wintest/lib/python3.7/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/Martin/opt/miniconda3/envs/wintest/lib/python3.7/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print("Ë´ãËº∏ÂÖ•‰∏âÈÇäÈï∑a,b,c")
a, b, c = float(input().split())
# a = float(input("a:"))
# b = float(input("b:"))
# c = float(input("c:"))
# print((a+b > c) & (a+c > b) & (b+c > a))


def helen(a, b, c):
    s = (a+b+c)/2
    area = (s*(s-a)*(s-b)*(s-c))**(1/2)
    print("Èù¢Á©çÊòØ", area)


if ((a+b > c) & (a+c > b) & (b+c > a)):
    helen(a, b, c)
else:
    print("ÈÄô‰∏çÊòØ‰∏âËßíÂΩ¢")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
[0;32m<ipython-input-4-9506b7a72649>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mprint[0m[0;34m([0m[0;34m"Ë´ãËº∏ÂÖ•‰∏âÈÇäÈï∑a,b,c"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0ma[0m[0;34m,[0m [0mb[0m[0;34m,[0m [0mc[0m [0;34m=[0m [0mfloat[0m[0;34m([0m[0minput[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0msplit[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;31m# a = float(input("a:"))[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;31m# b = float(input("b:"))[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;31m# c = float(input("c:"))[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/miniconda3/envs/wintest/lib/python3.7/site-packages/ipykernel/kernelbase.py[0m in [0;36mraw_input[0;34m(self, prompt)[0m
[1;32m    856[0m         [0;32mif[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0m_allow_stdin[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    857[0m             raise StdinNotImplementedError(
[0;32m--> 858[0;31m                 [0;34m"raw_input was called, but this frontend does not support input requests."[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    859[0m             )
[1;32m    860[0m         return self._input_request(str(prompt),

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

